name: CI Process
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  behave-testing:
    #Setup of simple OS of choice. i.e. Linux
    #create VM with ubuntu OS
    runs-on: ubuntu-latest

    steps:
      #Setup of environment for test
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List repo
        run: |
          ls
          
    #Setup tools necessary for testing, search from marketplace
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'
